### ISSUE TITLE
Error after "map" 

### ISSUE THREAD

**Issue by ngminhtrung** [XD-DENG/Spark-practice#6]
Hi,

After implemented the following code, I got an error which said "*AttributeError: 'DataFrame' object has no attribute 'map'*". Could you please have a check on this? Thank you!

```python
>>> content = raw_content.map(lambda x: x.split(','))
```

**Comment by XD-DENG** [comment]
I guess you didn’t run all the commands in order, or have re-run some of them?

May you try to start a new session and run commands in order? It should work then.

**Comment by allenbradely** [comment]
Instead of map try with flatmap..
